version: "3.7"
services:
  database:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=shortener
#    volumes:
#      - postgres-db:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    depends_on:
      - database
    env_file:
      - .env
    environment:
      - DB_TYPE=postgres
    ports:
      - "8081:8080"
    restart: unless-stopped
  gateway:
    build:
      context: .
      dockerfile: Dockerfile-api
    depends_on:
     - server
    ports:
      - "9091:9090"
#volumes:
#  postgres-db: