# syntax=docker/dockerfile:1

FROM golang:1.20
# install protoc into docker
WORKDIR /app
COPY ./bin/server .
#RUN make

# Optional:
# To bind to a TCP port, runtime parameters must be supplied to the docker command.
# But we can document in the Dockerfile what ports
# the application is going to listen on by default.
# https://docs.docker.com/engine/reference/builder/#expose
EXPOSE 8080
ENV PORT=5230
# Run
CMD ["/app/server"]
#docker build -f ./DockerFile -t url-shortener --no-cache .
