FROM golang:1.20-alpine
RUN mkdir /app
ADD . /app

WORKDIR /app

COPY go.mod go.sum ./
COPY .env .
RUN go mod download

RUN go build -o /bin/server ./cmd/server/main.go

EXPOSE 8080

CMD ["./bin/server"]