version: "3.7"
services:
  redis:
    image: redis:alpine
    command: redis-server
    restart: unless-stopped
#    volumes:
#      - redis_volume_data:/data
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    env_file:
      - .env
    environment:
      - DB_TYPE=redis
    depends_on:
      - redis
    ports:
      - "8081:8080"
    restart: unless-stopped
  gateway:
    build:
      context: .
      dockerfile: Dockerfile-api
    env_file:
      - .env
    depends_on:
      - server
    ports:
      - "9091:9090"
#volumes:
#  redis_volume_data:
