# syntax=docker/dockerfile:1

FROM golang:1.20
# install protoc into docker
WORKDIR /app
COPY ./bin/server .
COPY .env .
#RUN make

# Optional:
# To bind to a TCP port, runtime parameters must be supplied to the docker command.
# But we can document in the Dockerfile-api-server what ports
# the application is going to listen on by default.
# https://docs.docker.com/engine/reference/builder/#expose
EXPOSE 8080

CMD ["/app/server"]
#docker build -f ./Dockerfile-api-server -t url-shortener --no-cache .
